const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const UPDATE_NEW_TODO_VALUE = 'UPDATE_NEW_TODO_VALUE';
const SELECT_TODO = 'SELECT_TODO';
const DESELECT_TODO = 'DESELECT_TODO';
const UPDATE_TODO = 'UPDATE_TODO';

export default {
  ADD_TODO,
  REMOVE_TODO,
  UPDATE_NEW_TODO_VALUE,
  SELECT_TODO,
  UPDATE_TODO,
  DESELECT_TODO
};
